#!/bin/bash
 
NAME="%(proj_name)s"                                			# Name of the application
DJANGODIR=%(proj_path)s           								# Django project directory
SOCKFILE=%(venv_path)s/run/gunicorn.sock  						# we will communicte using this unix socket
USER=%(django_user)s               								# the user to run as
GROUP=%(django_user_group)s                                     # the group to run as
NUM_WORKERS=3                                     				# how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=project.settings             			# which settings file should Django use
DJANGO_WSGI_MODULE=project.wsgi                     			# WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source %(venv_path)s/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec %(venv_path)s/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE